### ISSUE TITLE
New feature: states!

### ISSUE THREAD

**Issue by feministy** [feministy/cryptozoologist#15]
**Summary**

👋 your task, should you choose to accept it, is to add states to Cryptozoologist.

**Acceptance criteria**

- As a user of the Cryptozoologist gem, I can call the method `Cryptozoologist.state` and be provided with a string that uses the internal dictionaries (your choice which dictionaries!) to make a state name (`Oregoose`, `Caterpillfornia`, `New Hamster`, `Scarlet Carolina` - your choice)
- As a user of the Cryptozoologist gem, I can find documentation in the `README` for how to use the new method
- As someone curious about the Cryptozoologist gem, I can view the version bump for these changes in the `CHANGELOG`
- As a contributor to the gem, I can run all of the tests and they pass!

**Technical requirements**

- If you want to add a new dictionary, you can, but make sure you follow the current namespacing patterns
- All new code should be tested, but I welcome in progress PRs for feedback on your code _before_ you write tests (this is optional!)

**Comment by feministy** [comment]
Important note: this can be as complicated or as easy as you make it. If you want a challenge, you can generate combined state names from real state names (ex: `Oregoose`), or you can make up state names 👍

**Comment by andrewmbyrd** [comment]
hello @feministy , I saw your listing on yourfirstpr repo. I've got a bit of experience with gems, I'd like to take a shot at this if you'd still like help!

**Comment by feministy** [comment]
yes please, go for it!

**Comment by feministy** [comment]
tag me when you get a PR up, even if it's just in progress, and i'll pop in with a code review!
