### ISSUE TITLE
Failing test for #lorem

### ISSUE THREAD

**Issue by isabarros** [feministy/cryptozoologist#18]
@feministy While running the tests for generator_spec found that the test on line 14 failed when generated the following sentence:

`White lambskin costume snaps and nightshirt darwin's frog the white tiger the dark salmon swan? Mandrill coral galoshes buxton blue beige caftan the at the buffalo x ray tetra beanie! Bra be there sunbonnet teddy floral white light blue cowboy hat to collared peccary australian shepherd white jackal absolute zero rugby shirt vervet monkey forest green leopard cat?`

It occurs because the animal string `darwin's frog` has a symbol.

**Comment by isabarros** [comment]
A possible solution that I just tried here would be to replace this [line](https://github.com/feministy/cryptozoologist/blob/master/spec/cryptozoologist/generator_spec.rb#L16) by `punctuation = sentence.scan(/[.|?|!]/)`

**Comment by feministy** [comment]
oh hey good catch!

did you want to fix this? no worries if not, i can take care of it 😎

**Comment by isabarros** [comment]
@feministy Sure, I can open a PR for that.
