### ISSUE TITLE
Failing test for #random

### ISSUE THREAD

**Issue by isabarros** [feministy/cryptozoologist#19]
In generator_spec on [line 43](https://github.com/feministy/cryptozoologist/blob/master/spec/cryptozoologist/generator_spec.rb#L43) the test fails when `random` value is:
```
oceans
gray
asian
giant
hornet
nightshirt
```
This happens because the animal string `asian giant hornet` has the word `giant` which is also in quantity list, so two words from the quantity list are found instead of 1.

**Comment by feministy** [comment]
oh damn, good catch!

**Comment by CaraHill** [comment]
I'll give this one a go.

**Comment by feministy** [comment]
fixed, yay!
